### ISSUE TITLE
UDF failed: name 'cs_winsorize_quantile' is not defined

### ISSUE THREAD

**Issue by FlashWB** [wukan1986/alpha_examples#1]
df = df.group_by(by=[_DATE_]).map_groups(func_2_cs__date)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\123\AppData\Roaming\Python\Python311\site-packages\polars\dataframe\group_by.py", line 322, in map_groups
    self.df._df.group_by_map_groups(
pyo3_runtime.PanicException: UDF failed: name 'cs_winsorize_quantile' is not defined

请问一下，为什么运行prepare_data.py报这个错

**Comment by wukan1986** [comment]
`codegen/1_label.py`运行后会自动更新`codes/labels.py`
