### ISSUE TITLE
Incorrect place for IC&IR

### ISSUE THREAD

**Issue by ToKaTEio** [wukan1986/alpha_examples#4]
The output of function fitness_population is (ic_train, ic_valid, ir_train, ir_valid), but following usage of this function seems to be (ic_train, ir_train, ic_valid, ir_valid), which may lead to incorrect calculation of fitness.

函数的输出和在batched_exprs函数中的使用顺序貌似不同，输出是(ic_train, ic_valid, ir_train, ir_valid)， 但是使用的时候是(ic_train, ir_train, ic_valid, ir_valid)

**Comment by wukan1986** [comment]
谢谢，已经更新
