### ISSUE TITLE
from expr_codegen.codes import source_replace, SympyTransformer报错

### ISSUE THREAD

**Issue by rk19016** [wukan1986/alpha_examples#7]
大佬，

请教一个问题，

在你的项目 alpha_examples/transformer/alpha101_transformer.py

from expr_codegen.codes import source_replace, SympyTransformer

你的项目 expr_codegen已经升级到0.9.0了。

对应的alpha101_transformer.py代码是否可以更新一下？

包括您在知乎 https://zhuanlan.zhihu.com/p/682068489 上的示例代码

raw, exprs_dict = sources_to_exprs(globals().copy(), source1, '\n'.join(source2), safe=False)

也需要修改下才能执行成功？

谢谢！

**Comment by wukan1986** [comment]
知乎上文章所附代码不再改动
